version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    networks:
      - backend
    ports:
      - 8080:8000
    links:
      - db:db_domain
    depends_on:
      - db

  db:
    container_name: db
    image: mariadb:10.5
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: mariadb
      MYSQL_ROOT_PASSWORD: secret

volumes:
  mariadb_data:

networks:
  backend:
    name: candy_delivery_api
    driver: bridge
