version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend
    ports:
      - 8080:8080
  #   links:
  #     - db:db_domain
  #   depends_on:
  #     - db

  # db:
  #   image: mariadb:10.5
  #   volumes:
  #     - db_volume:/var/lib/mysql
  #   networks:
  #     - backend
  #   ports:
  #     - 3306:3306
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: appdata
  #     MYSQL_USER: maria
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: secret

volumes:
  db_volume:

networks:
  backend:
    name: candy_delivery_api
    driver: bridge
